version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/drivebase?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecret_drivebase_jwt_access_key_2026
      - JWT_REFRESH_SECRET=supersecret_drivebase_jwt_refresh_key_2026
      - ENCRYPTION_KEY=drivebase_encryption_key_32_bytes_!
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: drivebase_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivebase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: drivebase_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
